# Raspberry Pi 3 hardware configuration (generated by nixos-generate-config)
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    # SD card image builder -- uncomment to rebuild a fresh SD image:
    #   nix build ".#nixosConfigurations.rpi3.config.system.build.sdImage"
    # (modulesPath + "/installer/sd-card/sd-image-aarch64.nix")
  ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

  fileSystems."/boot/firmware" =
    {
      device = "/dev/disk/by-uuid/2178-694E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Commented out to preserve space on 8 GB SD card (root is at 80% usage)
  # swapDevices = [{
  #   device = "/swapfile";
  #   size = 1024; # 1 GB
  # }];
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
