#!/usr/bin/env bash
#
# Rofi-based display/monitor configuration menu.
#

SCRIPT_DIR="$HOME/.config/i3/scripts/monitor"

#######################################################################
#                            BEGIN CONFIG                             #
#######################################################################

ROFI_OPTIONS=(-theme ~/.config/rofi/monitor-menu.rasi)

#######################################################################
#                             END CONFIG                              #
#######################################################################

typeset -A menu

menu=(
  [" External Only"]="$SCRIPT_DIR/external-only.sh"
  [" Extend Above"]="$SCRIPT_DIR/extend-above.sh"
  [" Extend Left"]="$SCRIPT_DIR/extend-left.sh"
  [" Extend Right"]="$SCRIPT_DIR/extend-right.sh"
  [" Mirror"]="$SCRIPT_DIR/mirror.sh"
  [" Disable"]="$SCRIPT_DIR/default.sh"
  [" Toggle Screensaver"]="$SCRIPT_DIR/toggle-screensaver.sh"
  [" Arandr"]="arandr"
)

menu_nrows=${#menu[@]}

launcher=(rofi -dmenu -i -lines "${menu_nrows}" -p "Display"
  "${ROFI_OPTIONS[@]}")

selection="$(printf '%s\n' "${!menu[@]}" | sort | "${launcher[@]}")"

if [[ $? -eq 0 && -n "${selection}" ]]; then
  cmd="${menu[${selection}]}"
  if [[ -n "${cmd}" ]]; then
    i3-msg -q "exec ${cmd}"
  fi
fi
