#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
source "$SCRIPT_DIR/audio-output-menu"

case $BLOCK_BUTTON in
1) select_output ;;
2) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
4) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ ;;
5) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- ;;
3) notify-send "📢 Volume module" "\- Shows volume 🔊, 🔇 if muted.
- Left click to select output.
- Middle click to mute.
- Scroll to change." ;;
9) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print 🔇 and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && echo 🔇 && exit

vol="${vol#Volume: }"

split() {
  # For ommiting the . without calling and external program.
  IFS=$2
  set -- $1
  printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

case 1 in
$((vol >= 70))) icon="🔊" ;;
$((vol >= 30))) icon="🔉" ;;
$((vol >= 1))) icon="🔈" ;;
*) echo 🔇 && exit ;;
esac

echo "$icon$vol%"
